import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import { useMoralis } from 'react-moralis'
import EnterLottery from '@/components/EnterLottery'


const inter = Inter({ subsets: ['latin'] })

const supportedChains = ["31337", "11155111"]
export default function Home() {
  const {isWeb3Enabled,chainId} = useMoralis()
  return (
    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-9/12 mx-auto border'>
        <Header/>
        <div>
          {isWeb3Enabled ? <div>
            {supportedChains.includes(parseInt(chainId).toString())?<div>
              <EnterLottery/>
            </div>:<div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>}
          </div>:
          <div><h2>Please Connect to Wallet</h2></div>}
        </div>
      </main>
    </>
  )
}
